### ISSUE TITLE
Sourcing rb file met with "Cross origin requests are only supported for HTTP" error

### ISSUE THREAD

**Issue by mcthomas** [woxtu/rbscript#1]
Is it still possible to use this script for executing ruby from an external src file, rather than directly in the HTML file?  When I attempt the example in the README, I receive the following error:

```
[Log]  (rbscript.umd.js, line 18)
[Error] Cross origin requests are only supported for HTTP.
	(anonymous function) (rbscript.umd.js:18:2253)
	asyncFunctionResume
	promiseReactionJob
[Error] Fetch API cannot load file:///path/to/my/file.rb due to access control checks.
	(anonymous function) (rbscript.umd.js:18:2253)
	asyncFunctionResume
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: Load failed
```

**Comment by woxtu** [comment]
You need to set up a local HTTP server because many browsers block loading local resources.
https://developer.mozilla.org/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

**Comment by mcthomas** [comment]
Thank you.
